# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-27 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='createdAt',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
