# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-27 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20170427_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='notes',
        ),
    ]
