# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-30 02:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20170429_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='createdAt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 30, 2, 6, 16, 753806)),
        ),
    ]
